version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: es02
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:9200:9200" # http 통신용
      - "127.0.0.1:9300:9300" # 노드간 내부 통신
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18
    container_name: kib02
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
